metadata:
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    welcome = Hello from Kubernetes ConfigMap!!!
    dummy = some value
  config.json: |+
    {
      "listeners": [
        {
          "port": 80,
          "filters": [
            {
              "type": "read",
              "name": "http_connection_manager",
              "config": {
                "access_log": [
                   {
                      "path": "/dev/stdout"
                   }
                ],
                "codec_type": "auto",
                "stat_prefix": "ingress_http",

                "route_config": {
                  "virtual_hosts": [
                    {
                      "name": "sb_webmvc_service",
                      "domains": ["*"],
                      "routes": [
                        {
                          "timeout_ms": 0,
                          "prefix": "/",
                          "cluster": "local_service"
                        }
                      ]
                    }
                  ]
                },
                "filters": [
                  {
                    "type": "decoder",
                    "name": "router",
                    "config": {}
                  }
                ]
              }
            }
          ]
        }
      ],
      "admin": {
        "access_log_path": "/tmp/envoy.log",
        "port": 8001
      },
      "cluster_manager": {
        "clusters": [
          {
            "name": "local_service",
            "connect_timeout_ms": 250,
            "type": "strict_dns",
            "lb_type": "round_robin",
            "hosts": [
              {
                "url": "tcp://127.0.0.1:8080"
              }
            ]
          }
        ]
      }
    }


