metadata:
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    welcome = Hello from Kubernetes ConfigMap!!!
  config.json: |+
    {
      "listeners": [{
        "port": 9001,
        "filters": [{
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "egress_http",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "ipaddress_service",
                  "domains": [
                    "ipaddress-service"
                  ],
                  "routes": [{
                    "timeout_ms": 0,
                    "prefix": "/",
                    "cluster": "ipaddress_service_cluster"
                  }]
                }]
            },
            "filters": [{
              "type": "decoder",
              "name": "router",
              "config": {}
            }]
          }
        }]
      }],
      "admin": {
        "access_log_path": "/tmp/admin_access.log",
        "port": 9901
      },
      "cluster_manager": {
        "clusters": [{
          "name": "ipaddress_service_cluster",
          "connect_timeout_ms": 250,
          "type": "logical_dns",
          "lb_type": "round_robin",
          "hosts": [{
            "url": "tcp://spring-boot-ipaddress-se:80"
          }]
        }]
      }
    }


